version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
  frontend:
    build:
        context: .
        dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
