version: '3'

services:
  frontend:
    build: .
    labels:
      shipyard.route: '/'
    ports:
      - '3000:3000'
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - 'dbdata:/app/data'

volumes:
  dbdata:

