version: '3'

services:

  frontend:
    build: .
    ports:
      - '3000:3000'
      - '3001:3001'
    env_file:
      - .env

  # backend:
  #   build: .
  #   volumes:
  #     - './src:/app/src'
  #     - './backend:/app/backend'
  #     - './scripts:/app/scripts'
  #     - './data:/app/data'
  #     - './tsconfig.json:/app/tsconfig.json'
  #     - './tsconfig.tsnode.json:/app/tsconfig.tsnode.json'
  #   ports:
  #     - '3001:3001'
