version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0

executors:
  with-chrome:
    docker:
      - image: 'cypress/base:16.0.0'


workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          executor: with-chrome
