version: 2.1

docker:
  - image: cypress/base:14.15.0


orbs:
  cypress: cypress-io/cypress@1.29.0
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          executor: cypress/base:14.15.0
