version: 2.1
orbs:
  cypress: cypress-io/cypress@1.20.0
workflows:
  build:
    jobs:
      - cypress/run:
          name: type checks
          command: yarn types
      - cypress/run:
          name: unit tests
          command: yarn test:unit
      - cypress/run:
          name: "API & Unit Tests"
          build: yarn build
          executor: cypress/browsers-chrome78-ff70
          browser: firefox
          yarn: true
          start: yarn test:ci
          wait-on: "http://localhost:3000"
          record: true
          spec: cypress/integration/api/*
      - cypress/run:
          name: "E2E Tests"
          build: yarn build
          executor: cypress/browsers-chrome78-ff70
          browser: chrome
          yarn: true
          start: yarn test:ci
          wait-on: "http://localhost:3000"
          record: true
          spec: cypress/integration/*.spec.ts
