name: "Perform end-to-end tests with Nullstone"
on:
  pull_request:
    types: [labeled]

env:
  NULLSTONE_ORG: nullstone
  NULLSTONE_STACK: demo-cypress

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  ephemeral-env-up:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.create.outputs.env_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Nullstone
        uses: nullstone-io/setup-nullstone-action@v0
      - id: create
        name: Create Ephemeral Env
        run: |
          env_name=$(nullstone envs new --preview --name="${{ github.head_ref }}-${{ github.event.pull_request.id }}")
          echo "env_name=${env_name}" >> "$GITHUB_OUTPUT"
          echo "NULLSTONE_ENV=${env_name}" >> $GITHUB_ENV
          echo "New unique environment name: ${env_name}"
      - name: Launch Ephemeral Env
        run: nullstone envs up
  ephemeral-env-down:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [e2e-tests]
    steps:
      - name: Set up Nullstone
        uses: nullstone-io/setup-nullstone-action@v0
      - name: Destroy ephemeral env
        env:
          NULLSTONE_ENV: ${{ needs.ephemeral-env-up.outputs.env_name }}
        run: nullstone envs down
  deploy:
    runs-on: ubuntu-latest
    needs: [build, ephemeral-env-up]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Nullstone
        uses: nullstone-io/setup-nullstone-action@v0
      - name: Deploy
  e2e-tests:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'e2e'
    needs: [deploy]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Nullstone
        uses: nullstone-io/setup-nullstone-action@v0
      - name: Deploy
        run: echo "Implement me"
      - name: Run seeds
        run: nullstone exec --app=realworld-migrations
      - name: Run tests
